---
driver:
  name: vagrant
  network:
    - ["private_network", {ip: "192.168.33.33"}]

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.4

suites:
  - name: server
    run_list:
      - recipe[zabbix-jp::postgresql]
      - recipe[zabbix-jp::server]
    attributes:
