---
driver:
  name: docker
  # socket: tcp://192.168.59.103:2375 # local

provisioner:
  name: chef_solo

platforms:
  - name: centos6
    driver_config:
      image: centos:centos6
      platform: centos

suites:
  - name: server
    run_list:
      - recipe[zabbix-jp::server]
    attributes:
